src/Entity/Post.php
<?php


namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class Post
 * @package App\Entity
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Post
{

    /**
     * Post constructor.
     */
    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->likes = new ArrayCollection();
        $this->tags = new ArrayCollection();
        $this->tag = new ArrayCollection();
    }

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="post", cascade={"persist", "remove"})
     * @ORM\OrderBy({"createdAt"="DESC"})
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PostLike", mappedBy="post", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $likes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Tag", mappedBy="post", cascade={"persist"})
     */
    private $tag;

    /**
     * @return Collection|Comment[]
     */
    public function getComments()
    {
        return $this->comments;
    }

    /**
     * @return Collection|PostLike[]
     */
    public function getLikes()
    {
        return $this->likes;
    }

    /**
     * @param Comment $comment
     * @return $this
     */
    public function addComment(Comment $comment)
    {
        if (!$this->comments->contains($comment)) {
            $comment->setPost($this);
            $this->comments[] = $comment;
        }
        return $this;
    }

    /**
     * @param Comment $comment
     * @return $this
     */
    public function removeComment(Comment $comment)
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }
        return $this;
    }

    public function addLike(PostLike $like)
    {
        if (!$this->likes->contains($like)) {
            $like->setPost($this);
            $this->likes[] = $like;
        }
        return $this;
    }

    /**
     * @param PostLike $like
     * @return $this
     */
    public function removeLike(PostLike $like)
    {
        if ($this->likes->contains($like)) {
            $this->likes->removeElement($like);
            if ($like->getPost() === $this) {
                $like->setPost(null);
            }
        }
        return $this;
    }

    /**
     * @return int
     */
    public function getLikesCount()
    {
        return $this->likes->count();
    }

    /**
     * @return mixed
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param mixed $createdAt
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @ORM\PrePersist()
     */
    public function onPrePersist()
    {
        $this->createdAt = new \DateTime('now');
    }

    public function getId()
    {
        return $this->id;
    }

    /**
     * @param $id
     * @return Post
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * @param string $content
     * @return Post
     */
    public function setContent($content)
    {
        $this->content = $content;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user)
    {
        $this->user = $user;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTag(): Collection
    {
        return $this->tag;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tag->contains($tag)) {
            $this->tag[] = $tag;
            $tag->setPost($this);

            $this->tags->add($tag);
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tag->contains($tag)) {
            $this->tag->removeElement($tag);
            // set the owning side to null (unless already changed)
            if ($tag->getPost() === $this) {
                $tag->setPost(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank()
     * @Assert\Email()
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     */
    private $firstName;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     */
    private $lastName;

    public function getFullName()
    {
        return $this->getFirstName() . ' ' . $this->getLastName();
    }

    /**
     * @return mixed
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * @param mixed $firstName
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;
    }

    /**
     * @return mixed
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * @param mixed $lastName
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Post;
use App\Entity\PostLike;
use App\Form\CommentFormType;
use App\Form\PostFormType;
use App\Repository\PostLikeRepository;
use App\Repository\PostRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class PostController extends AbstractController
{
    /**
     * @Route("/", name="post_index")
     * @param Request $request
     * @param EntityManagerInterface $entityManager
     * @param PostRepository $postRepository
     * @return Response
     */
    public function index(Request $request, EntityManagerInterface $entityManager, PostRepository $postRepository)
    {
        $form = $this->createForm(PostFormType::class);
        $form->handleRequest($request);
        if ($this->isGranted('ROLE_USER') && $form->isSubmitted() && $form->isValid()) {
            /** @var Post $post */
            $post = $form->getData();
            $post->setUser($this->getUser());
            $entityManager->persist($post);
            $entityManager->flush();
            $this->addFlash('success', 'New post created!');
            return $this->redirectToRoute('post_index');
        }

        $formSearch = $this->createFormBuilder(null)
            ->add('query', TextareaType::class)
            ->add('search', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-primary'
                ]
            ])->getForm();

        $formSearch->handleRequest($request);
        if($formSearch->isSubmitted() && $formSearch->isValid()) {
            $postsFind = $formSearch->getData();
            $posts = $postRepository->getByTag($postsFind['query']);
        } else {
            $posts = $postRepository->getAllInLastWeek();
        }
        return $this->render('post/index.html.twig', [
            'form' => $form->createView(),
            'posts' => $posts,
            'formSearch' => $formSearch->createView()
        ]);
    }

    /**
     * @Route("/view/{id}", name="post_view")
     * @param Post $post
     * @param Request $request
     * @param EntityManagerInterface $entityManager
     * @param PostLikeRepository $likeRepository
     * @return Response
     */
    public function show(Post $post, Request $request, EntityManagerInterface $entityManager, PostLikeRepository $likeRepository)
    {
        $form = $this->createForm(CommentFormType::class);
        $form->handleRequest($request);
        if ($this->isGranted('ROLE_USER') && $form->isSubmitted() && $form->isValid()) {
            /** @var Comment $comment */
            $comment = $form->getData();
            $comment->setUser($this->getUser());
            $post->addComment($comment);
            $entityManager->flush();
            return $this->redirectToRoute('post_view', [
                'id' => $post->getId()
            ]);
        }
        $userLikesPost = $likeRepository->findOneBy([
            'user' => $this->getUser(),
            'post' => $post
        ]);
        return $this->render('post/view.html.twig', [
            'post' => $post,
            'commentForm' => $form->createView(),
            'userLikesPost' => $userLikesPost
        ]);
    }

    /**
     * @Security("user == post.getUser()")
     * @Route("/post/{id}/delete", name="post_delete")
     * @param Post $post
     * @param EntityManagerInterface $entityManager
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deletePost(Post $post, EntityManagerInterface $entityManager)
    {
        $entityManager->remove($post);
        $entityManager->flush();
        $this->addFlash('success', 'Successfully deleted!');
        return $this->redirectToRoute('post_index');
    }

    /**
     * @IsGranted("ROLE_USER")
     * @Route("/post/{id}/like", name="post_like", methods={"POST"})
     * @param Post $post
     * @param EntityManagerInterface $entityManager
     * @param PostLikeRepository $likeRepository
     * @return JsonResponse
     */
    public function likePost(Post $post, EntityManagerInterface $entityManager, PostLikeRepository $likeRepository)
    {
        $like = $likeRepository->findOneBy([
            'user' => $this->getUser(),
            'post' => $post
        ]);

        if (!$like) {
            $like = new PostLike();
            $like->setUser($this->getUser());
            $post->addLike($like);
        } else {
            $post->removeLike($like);
        }

        $entityManager->flush();
        return new JsonResponse([
            'likes' => $post->getLikesCount()
        ]);
    }
}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {{ form(formSearch) }}
    {% if is_granted('ROLE_USER') %}
        {{ form_start(form) }}
        {{ form_errors(form, {'attr': {'novalidate': 'novalidate'}}) }}
        {{ form_row(form.content) }}
        <ul class="tags" data-prototype="{{ form_widget(form.tags.vars.prototype)|e('html_attr') }}">
            {# iterate over each existing tag and render its only field: name #}
            {% for tag in form.tags %}
                <li>{{ form_row(tag.content, {'attr': {'novalidate': 'novalidate'}}) }}</li>
            {% endfor %}
        </ul>
        <button type="submit" class="btn btn-primary" formnovalidate>Save</button>
        {{ form_end(form) }}
    {% endif %}

    {% for post in posts %}
        <div class="row mt-3">
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <h6 class="card-subtitle mt-2 text-muted">{{ post.createdAt|date }}</h6>
                        <p class="card-text">{{ post.content }}</p>
                        <a href="{{ path('post_view', {'id': post.id}) }}" class="card-link">Details</a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/tag.js') }}"></script>
{% endblock %}

templates/post/view.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row mt-3">
        <div class="col-lg-12">
            <div class="jumbotron">
                <div class="row">
                    <div class="col-lg-3">
                        <p class="text-muted">{{ post.createdAt|date }}</p>
                    </div>
                    <div class="col-lg-9 text-right">
                        {% if app.user == post.user %}
                            <a href="{{ path('post_delete', {id: post.id}) }}" class="btn btn-danger">Delete</a>
                        {% endif %}
                    </div>
                </div>
                <p>{{ post.content }}</p>
                {% if is_granted('ROLE_USER') %}
                    <a href="{{ path('post_like', {id: post.id}) }}"
                       class="fa{% if userLikesPost %}s{% else %}r{% endif %} fa-heart" id="post-likes">
                        ({{ post.likesCount }})
                    </a>
                {% else %}
                    Likes: {{ post.likesCount }}
                {% endif %}
            </div>
        </div>
    </div>

    {% if is_granted('ROLE_USER') %}
        {{ form_start(commentForm) }}
            {{ form_row(commentForm.content) }}
            <button type="submit" class="btn btn-primary" formnovalidate>Save</button>
        {{ form_end(commentForm) }}
    {% endif %}

    {% for comment in post.comments %}
        <div class="row mt-3">
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <h6 class="card-subtitle mt-2 text-muted">{{ comment.createdAt|date }}</h6>
                        <h5 class="card-title">{{ comment.user.fullName }} says:</h5>
                        <p class="card-text">{{ comment.content }}</p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/post_likes.js') }}"></script>
{% endblock %}